title: Bruno A. Veloso
email: brunoavn@df.ufscar.br
baseurl: ""
url: "https://brunoavn.github.io"
title: Bruno A. Veloso
email: brunoavn@df.ufscar.br
baseurl: ""
url: "https://brunoavn.github.io"
theme: minima
repository: brunoavn/brunoavn.github.io